name: 💚 Nost unit test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.71.0

      - name: Run tests
        run: cargo test
